// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tglfzozuqjvutthifreg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbGZ6b3p1cWp2dXR0aGlmcmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NzQ0ODYsImV4cCI6MjA1ODU1MDQ4Nn0.F0J-pBZZgIypO284HA1vC4tmVw-ZUQIHY-UH1NCx0cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);